version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "vue"
        versions: [">= 3.0.0"]
      - dependency-name: "vue-loader"
        versions: [">= 16.0.0"]
