# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Docs

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: imaegoo/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.TWIKOO_TOKEN }}
          TARGET_REPO: imaegoo/twikoo
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn global add vuepress@1.8.0 && vuepress build docs
          BUILD_DIR: docs/.vuepress/dist
          CNAME: twikoo.js.org
